### ISSUE TITLE
后台运行建议

### ISSUE THREAD

**Issue by Dipper-utlimate** [siriusnouers/sgs#1]
可以用adb命令来模拟点击或者用系统调用函数向窗口发送消息达到后台运行效果。你的代码写得不错，以后游戏自动化脚本可以用来参考。

**Comment by Dipper-utlimate** [comment]
话说作者怎么快速判断蓝色边框，用yolo训练数据集检测效果好，但是电脑资源消耗高；使用边缘检测识别率不高经常因为武将颜色的干扰失败。在排位模式有智能辅助功能，会在下一步操作上亮蓝框，所以可以试着脚本检测自动排位上分

**Comment by 2468785842** [comment]
adb有延迟,使用uiautomator2更好,我自己改了个uiautomator2版本的可以后台运行, [sgs_automatic_uiautomator2.py](https://github.com/2468785842/sgs/blob/master/sgs_automatic_uiautomator2.py)
