### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by Qjoinkk** [siriusnouers/sgs#4]
![image](https://github.com/user-attachments/assets/2c2aeea6-2b57-471e-84a3-231b15cb8ed9)

game_window = gw.getWindowsWithTitle('雷电模拟器')[0]  # 替换为实际的游戏窗口标题
IndexError: list index out of range 
请问大佬 这问题如何解决

**Comment by siriusnouers** [comment]
运行后快速切屏到雷电模拟器即可
