### ISSUE TITLE
能提供具体版本吗

### ISSUE THREAD

**Issue by mofomake** [siriusnouers/sgs#8]
能提供python的版本以及库的具体版本吗？我这边使用报错但是又能运行，但是运行又有问题，用了几次发现有时候会拉断有时候又不会，另外就是不管成功与否我这边都只执行一次，一直卡在第一次循环，也不结束

**Comment by siriusnouers** [comment]
![W)Y_7 ZXAKW~P`R CPF%TBA](https://github.com/user-attachments/assets/28315b4b-cf0d-46a6-918e-b892c146a4a7)

有些包可能是不需要的，python是3.10

**Comment by siriusnouers** [comment]
拉断可能是old_speed太低了，可以适当调高些
