### ISSUE TITLE
鱼王钓不了

### ISSUE THREAD

**Issue by jingzhe096** [siriusnouers/sgs#9]
需要致命一击才能钓的鱼钓不了，进入致命一击后程序就出错了，其他鱼可以正常钓

![image](https://github.com/user-attachments/assets/4855d164-b39c-49d3-b138-73bee62953fc)

**Comment by siriusnouers** [comment]
图片路径改了吗，再就是路径里好像不能有中文（有些忘了，应该都可以掉的）

**Comment by siriusnouers** [comment]
路径我弄的绝对路径，需要自己改一下
![image](https://github.com/user-attachments/assets/19bf24ac-751f-4bad-8a39-be9e3b7b3102)

**Comment by jingzhe096** [comment]
> 图片路径改了吗，再就是路径里好像不能有中文（有些忘了，应该都可以掉的）

路径有改。确实是中文的原因，我把中文改成英文就正常了
